# Generated by Django 3.2.4 on 2021-06-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
