# Generated by Django 3.2.4 on 2021-06-28 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
        ('rent', '0002_alter_rent_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.car'),
        ),
    ]
