# Generated by Django 3.2.4 on 2021-06-28 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
        ('rent', '0003_alter_rent_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car'),
        ),
    ]
